# Generated by Django 5.2.7 on 2025-10-14 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedimage',
            name='image_url',
            field=models.ImageField(upload_to='feed_images/'),
        ),
    ]
