# Generated by Django 5.2.7 on 2025-10-15 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feed_app', '0002_alter_feedimage_image_url'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feedimage',
            old_name='image_url',
            new_name='image',
        ),
    ]
